export const T = {
  ink: '#1b2330',
  sub: '#5d6b7a',
  faint: '#94a0ae',
  line: '#e6e1d8',
  lineSoft: '#f0ece4',
  paper: '#faf8f4',
  panel: '#ffffff',
  navy: '#1f3a5f',
  navyInk: '#15293f',
  navySoft: '#eef2f7',
  match: '#1f7a52',
  matchBg: '#e9f3ed',
  diff: '#9a5b16',
  diffBg: '#fbf1dd',
  diffMark: '#f4d79f',
  reject: '#a3372e',
  rejectBg: '#f8e9e6',
  serif: "'Source Serif 4', Georgia, serif",
  sans: "'Public Sans', system-ui, sans-serif",
  mono: "'IBM Plex Mono', ui-monospace, monospace",
}
